# Generated by Django 2.2.5 on 2019-09-07 23:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0002_auto_20190907_2324'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='lender',
        ),
    ]
