# Generated by Django 2.2.5 on 2019-09-07 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0003_remove_trip_lender'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='lender',
            field=models.ManyToManyField(to='rent.Lender'),
        ),
    ]
