# Generated by Django 2.2.5 on 2019-09-08 01:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0004_trip_lender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='car',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trips', to='rent.Car'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='lender',
            field=models.ManyToManyField(related_name='case', to='rent.Lender'),
        ),
    ]
