# Generated by Django 2.2.5 on 2019-09-09 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0005_auto_20190908_0135'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='car',
        ),
        migrations.AddField(
            model_name='trip',
            name='car',
            field=models.ManyToManyField(related_name='trips', to='rent.Car'),
        ),
    ]
