# Generated by Django 2.2.5 on 2019-09-09 19:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0006_auto_20190909_1930'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='lender',
        ),
        migrations.AddField(
            model_name='trip',
            name='lender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='case', to='rent.Lender'),
        ),
    ]
