# Generated by Django 2.2.5 on 2019-09-09 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0009_auto_20190909_2029'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trip',
            old_name='distance_km',
            new_name='distance_in_km',
        ),
    ]
