# Generated by Django 2.2.5 on 2019-09-09 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0011_auto_20190909_2141'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='price_for_a_day',
            field=models.IntegerField(null=True),
        ),
    ]
