# Generated by Django 2.2.5 on 2019-09-09 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0012_car_price_for_a_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='car',
            field=models.ManyToManyField(default=1, related_name='trips', to='rent.Car'),
        ),
    ]
