# Generated by Django 2.2.5 on 2019-09-10 00:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0014_auto_20190909_2348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='car',
            field=models.ManyToManyField(blank=True, default=1, related_name='trips', to='rent.Car'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='lender',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='case', to='rent.Lender'),
        ),
    ]
