# Generated by Django 2.2.5 on 2019-09-10 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0015_auto_20190910_0000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='client_name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
