# Generated by Django 2.2.5 on 2019-09-11 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0017_auto_20190911_1700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lender',
            name='lender_name',
            field=models.CharField(max_length=20),
        ),
    ]
