# Generated by Django 2.2.5 on 2019-09-11 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0018_auto_20190911_1702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='model',
            field=models.CharField(max_length=20),
        ),
    ]
