# Generated by Django 2.2.5 on 2019-09-11 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0019_auto_20190911_1703'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='car',
            field=models.ManyToManyField(related_name='trips', to='rent.Car'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='client_name',
            field=models.CharField(max_length=50),
        ),
    ]
