# Generated by Django 2.2.5 on 2019-09-11 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0022_auto_20190911_1837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='how_many_days',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='trip',
            name='price_for_one_day',
            field=models.PositiveIntegerField(),
        ),
    ]
