# Generated by Django 2.2.5 on 2019-09-19 10:34

from django.db import migrations, models
import rent.validators


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0023_auto_20190911_1847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='model',
            field=models.CharField(max_length=20, validators=[rent.validators.validate_model_name]),
        ),
        migrations.AlterField(
            model_name='car',
            name='price_for_a_day',
            field=models.PositiveIntegerField(),
        ),
    ]
