# Generated by Django 2.2.5 on 2019-10-02 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0023_auto_20190911_1847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lender',
            name='lender_name',
            field=models.TextField(max_length=20),
        ),
    ]
