# Generated by Django 2.2.5 on 2019-10-03 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0024_auto_20191002_2144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='client_name',
            field=models.TextField(max_length=50),
        ),
    ]
