# Generated by Django 2.2.5 on 2019-10-16 20:38

from django.db import migrations, models
import rent.validators


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0025_auto_20191003_0032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='model',
            field=models.CharField(max_length=100, validators=[rent.validators.validate_model]),
        ),
    ]
